http:
  port: 9000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  paksat:
    host: localhost
    paths: '/Safi'
  symNotify:
    host: localhost
    paths: '/Muneefah'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  servicePaksat:
    url: 'http://localhost:9900'
  serviceSymNotify:
    url: 'http://localhost:3001'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  paksatsPipeline:            
    apiEndpoints:
      - paksat
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: servicePaksat 
              changeOrigin: true
  symNotifyPipeline:            
    apiEndpoints:
      - symNotify
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: serviceSymNotify 
              changeOrigin: true